---
room_name: spare

blackmagic_sources:
- card: 0
  connection: SDI
  audio: true

sources:
- Camera
- Grabber

eth_local_ip_address: 10.17.0.1
eth_local_ip_netmask: 24
eth_local_ip_gateway: 10.17.0.1
eth_local_mac_address: 2c:41:38:92:47:9e
eth_uplink_mac_address: 8a:ce:4c:ff:ae:83
