---
user_password_crypted: "$6$MY/oz4fhX$oAM.iSDVAPljLLD5c8.YF/.sBv05K/aGlHIzHHxQ7kw5eyiMtdzpZW0PFrt3K9ppdWQiP.h6M4NppUW4vV7X0."

org: pyconza
show: pyconza2017
# room:

time_zone: Africa/Johannesburg

domain: video.pyconza
#dhcp_range: 10.17.0.128,10.17.0.254,6h

distro: Ubuntu
debian_version: xenial

mirror: za.archive.ubuntu.com
apt_proxy: false

# Git repos:
playbook_repo: https://anonscm.debian.org/cgit/debconf-video/ansible.git
playbook_branch: master

# To replace the stock inventory with your own, point at your own github repo
inventory_repo: https://github.com/CTPUG/pyconza2017-video.git
inventory_branch: master

netboot_image: http://archive.ubuntu.com/ubuntu/dists/xenial/main/installer-amd64/current/images/netboot/netboot.tar.gz

blackmagic:
  desktopvideo: http://gw/bm/Blackmagic_Desktop_Video_Linux_10.9.7a2/deb/amd64/desktopvideo_10.9.7a2_amd64.deb
  desktopvideo-gui: http://gw/bm/Blackmagic_Desktop_Video_Linux_10.9.7a2/deb/amd64/desktopvideo-gui_10.9.7a2_amd64.deb
  dkms_version: 10.9.7a2

public_keys_onsite:
- ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAgEAwnx+CG/lqDIUwzAYNYsMxVgQTPvfZgo/O6SJgWwyKcv/079juf/VyrI77L/CpA2uF8NeQkd+ZXI8MnnDCCO6iIasmUIHo9qH+Yn8PjzxbhuM9MHA5hKkSmlEOSN0avAjg0WhRHp+ofHPM8TQMP/+ZGBU5FaDHvhfu7J1ZwErDug/NWhbg/anICUzXyYmqvqyZu3+onW9PE1pjmfUrpGYC3K3zHqFAfw3yrwCHiJdBR7xJpmmwVA0iKtSBSO/lssRsGhCuVRzGIPdexC8sLNdPAuMX5nwRMx+NWlhUxjF3fn2fGtGa3ZUhjEOgD8KaPHobpB0emp+iXe5U/Y/4y6Xo85VKwk287KruHl5heoejIvIFcu7GnXdo5XTmYUz6Z5fHhTOfmBIlXI9Wo06dDe1Zk3qFuJ+FoxTzvtC6yUSVsrqLt7FmCZcPUSbp5hBMh0aO8gM5HI09fBamhK565QxLQgHvkHaOC7r+PEbqGPgKGq2mxwlJEMpPyuObbtCp4rOBBi2Ot5cIyhLFryht0DwajkX1QSkPoNP1Teozr3S1e28FKYVTZGLQeMtTPSaXVHF3HMTAWWODBifrFTIJQZsyPDvlMCd8xgtfECldRwyq0yFVJkNuxQRMQeYFV3uyUuRc4+cdAlBXhsY64sqP5fAH/msRx0zOHwBRHc1S85K32M= stefanor
- ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICNAli0vujO4LN9K/8NY8NkLdAQycoXX+MgqvZAnIrMC froztbyte@pebbles
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC15kvgEiLf7pJXPPTwYPTo55GhIQNOfZ97zBgaIy1q9omtnl9D01taIMRR6RVhojgAtXlAbncUy1jnNPi6FqxECNfOhsYQTe0fl2M9G2r2JHp4zFddSPDsMd3fMosg3YPdPjOg3Tb7HuMWwIu6XCLukFBeYbuFYy6ccsOZOLgbY8qAE4XBeTzAcO6337lmhHUc5FJXxudgDHzi9KA98HR1LQvjuxJv0I11kUXjSJsu7ZUvCmLaXQG8oR0nN36tfmU2ac8ogr+5f6t5ttTKzeN/biSfUXcDy9zLTVW1QnxUegz2Y5QhdAWyd0kLCSIj6mUXF5iq+fWzGPt21Kwn/FYgO5jwPEtjTEMB7LJArCIOsgB5VXAn5hRS/YSId13gOc51M/cnFe+zGKWpXzboG7DvNN7PckLoIRiA6H5iK9iYMzko87H2W8bZFIkuVAh1ChogWcbENstzqF/N7/UMZoC9FOhtKha2Rf009bfY71TbVHiAT4WTUUHjTbF4dki9rfvN8ZDoHqySyliof0L3szMdxaFwAHS3RW871DBW5L/w8K2CScg+VVvCSQ92iLbYNZXnPwnlymq82wZG5cdbpg+W4RzvkNPYuj8ZQI58AInLDUzwiIqUgGPPH4FRd8lbX53W6unpyVpiv5CF5c92UC1MT/qj8DVbApcfDCCE2MXQcQ== krobbertze@gmail.com

public_keys_root:
- ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAgEAwnx+CG/lqDIUwzAYNYsMxVgQTPvfZgo/O6SJgWwyKcv/079juf/VyrI77L/CpA2uF8NeQkd+ZXI8MnnDCCO6iIasmUIHo9qH+Yn8PjzxbhuM9MHA5hKkSmlEOSN0avAjg0WhRHp+ofHPM8TQMP/+ZGBU5FaDHvhfu7J1ZwErDug/NWhbg/anICUzXyYmqvqyZu3+onW9PE1pjmfUrpGYC3K3zHqFAfw3yrwCHiJdBR7xJpmmwVA0iKtSBSO/lssRsGhCuVRzGIPdexC8sLNdPAuMX5nwRMx+NWlhUxjF3fn2fGtGa3ZUhjEOgD8KaPHobpB0emp+iXe5U/Y/4y6Xo85VKwk287KruHl5heoejIvIFcu7GnXdo5XTmYUz6Z5fHhTOfmBIlXI9Wo06dDe1Zk3qFuJ+FoxTzvtC6yUSVsrqLt7FmCZcPUSbp5hBMh0aO8gM5HI09fBamhK565QxLQgHvkHaOC7r+PEbqGPgKGq2mxwlJEMpPyuObbtCp4rOBBi2Ot5cIyhLFryht0DwajkX1QSkPoNP1Teozr3S1e28FKYVTZGLQeMtTPSaXVHF3HMTAWWODBifrFTIJQZsyPDvlMCd8xgtfECldRwyq0yFVJkNuxQRMQeYFV3uyUuRc4+cdAlBXhsY64sqP5fAH/msRx0zOHwBRHc1S85K32M= stefanor
- ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICNAli0vujO4LN9K/8NY8NkLdAQycoXX+MgqvZAnIrMC froztbyte@pebbles
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC15kvgEiLf7pJXPPTwYPTo55GhIQNOfZ97zBgaIy1q9omtnl9D01taIMRR6RVhojgAtXlAbncUy1jnNPi6FqxECNfOhsYQTe0fl2M9G2r2JHp4zFddSPDsMd3fMosg3YPdPjOg3Tb7HuMWwIu6XCLukFBeYbuFYy6ccsOZOLgbY8qAE4XBeTzAcO6337lmhHUc5FJXxudgDHzi9KA98HR1LQvjuxJv0I11kUXjSJsu7ZUvCmLaXQG8oR0nN36tfmU2ac8ogr+5f6t5ttTKzeN/biSfUXcDy9zLTVW1QnxUegz2Y5QhdAWyd0kLCSIj6mUXF5iq+fWzGPt21Kwn/FYgO5jwPEtjTEMB7LJArCIOsgB5VXAn5hRS/YSId13gOc51M/cnFe+zGKWpXzboG7DvNN7PckLoIRiA6H5iK9iYMzko87H2W8bZFIkuVAh1ChogWcbENstzqF/N7/UMZoC9FOhtKha2Rf009bfY71TbVHiAT4WTUUHjTbF4dki9rfvN8ZDoHqySyliof0L3szMdxaFwAHS3RW871DBW5L/w8K2CScg+VVvCSQ92iLbYNZXnPwnlymq82wZG5cdbpg+W4RzvkNPYuj8ZQI58AInLDUzwiIqUgGPPH4FRd8lbX53W6unpyVpiv5CF5c92UC1MT/qj8DVbApcfDCCE2MXQcQ== krobbertze@gmail.com

streaming:
  method: rtmp
  rtmp:
    threads: 2
    location: "rtmp://a.rtmp.youtube.com/live2/x/{{ youtube_auth }} app=live2"
  hq_config:
    video_bitrate: 1000 # kbps
    audio_bitrate: 96000 # bps
    keyframe_period: 100

serial_terminal:
- cu

sources:
- Camera
- Grabber

staticips:
  hosts:
  - hostname: gw
    mac: 2c:41:38:92:47:9e
    ip: 10.17.0.1
  - hostname: voctomix1
    mac: 3c:d9:2b:79:b1:1f
    ip: 10.17.0.10
  - hostname: odroid1
    mac: 00:1e:06:33:5a:36
    ip: 10.17.0.11
  - hostname: voctomix2
    mac: 2c:41:38:92:47:a4
    ip: 10.17.0.20
  - hostname: odroid2
    mac: 00:1e:06:33:59:9a
    ip: 10.17.0.21
  - hostname: voctomix3
    mac: 3c:d9:2b:79:b1:16
    ip: 10.17.0.30
  - hostname: odroid3
    mac: 00:1e:06:33:c8:6c
    ip: 10.17.0.31
  - hostname: odroid4
    mac: 00:1e:06:33:81:a0
    ip: 10.17.0.41
  gateway: 10.17.0.1

voctomix:
  display_system: gl
  framerate: 25
  loop_url: http://gw/loop.tar

rsync_excludes: []
rsync_sshopts: null
storage_username: videoteam
nfs_server: gw
